id: AD6F55F5C
title: Aspiration to Be Reborn at the Vajra Seat (Bodhgayā), Akaniṣṭha on Earth
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:59:03.616644
  last_modified_at: 2022-03-01 03:59:03.616652
